# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.

package WSO2::WSF::C;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package WSO2::WSF::Cc;
bootstrap WSO2::WSF::C;
package WSO2::WSF::C;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package WSO2::WSF::C;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package WSO2::WSF::C;

*axiom_document_build_all = *WSO2::WSF::Cc::axiom_document_build_all;
*axutil_env_create_all = *WSO2::WSF::Cc::axutil_env_create_all;
*axis2_endpoint_ref_create = *WSO2::WSF::Cc::axis2_endpoint_ref_create;
*axis2_options_create = *WSO2::WSF::Cc::axis2_options_create;
*axis2_options_set_action = *WSO2::WSF::Cc::axis2_options_set_action;
*axis2_svc_client_create = *WSO2::WSF::Cc::axis2_svc_client_create;
*axis2_svc_client_set_options = *WSO2::WSF::Cc::axis2_svc_client_set_options;
*axis2_svc_client_engage_module = *WSO2::WSF::Cc::axis2_svc_client_engage_module;
*axiom_namespace_create = *WSO2::WSF::Cc::axiom_namespace_create;
*axiom_element_create = *WSO2::WSF::Cc::axiom_element_create;
*axiom_element_set_text = *WSO2::WSF::Cc::axiom_element_set_text;
*axiom_node_to_string = *WSO2::WSF::Cc::axiom_node_to_string;
*axis2_svc_client_send_receive = *WSO2::WSF::Cc::axis2_svc_client_send_receive;
*axutil_log_impl_log_error = *WSO2::WSF::Cc::axutil_log_impl_log_error;
*axiom_xml_reader_create_for_memory = *WSO2::WSF::Cc::axiom_xml_reader_create_for_memory;
*axiom_xml_reader_create_for_memory_new = *WSO2::WSF::Cc::axiom_xml_reader_create_for_memory_new;
*axiom_stax_builder_create = *WSO2::WSF::Cc::axiom_stax_builder_create;
*axiom_stax_builder_get_document = *WSO2::WSF::Cc::axiom_stax_builder_get_document;
*axiom_document_get_root_element = *WSO2::WSF::Cc::axiom_document_get_root_element;
*axis2_qname_create = *WSO2::WSF::Cc::axis2_qname_create;
*axis2_qname_get_prefix = *WSO2::WSF::Cc::axis2_qname_get_prefix;
*axiom_soap_envelope_create = *WSO2::WSF::Cc::axiom_soap_envelope_create;
*axutil_qname_to_string = *WSO2::WSF::Cc::axutil_qname_to_string;
*axiom_node_serialize = *WSO2::WSF::Cc::axiom_node_serialize;
*axiom_xml_writer_create_for_memory = *WSO2::WSF::Cc::axiom_xml_writer_create_for_memory;
*axiom_output_create = *WSO2::WSF::Cc::axiom_output_create;
*axis2_svc_client_get_options = *WSO2::WSF::Cc::axis2_svc_client_get_options;
*axis2_options_set_to = *WSO2::WSF::Cc::axis2_options_set_to;
*axis2_libxml2_writer_wrapper_get_xml = *WSO2::WSF::Cc::axis2_libxml2_writer_wrapper_get_xml;
*axis2_svc_client_get_svc_ctx = *WSO2::WSF::Cc::axis2_svc_client_get_svc_ctx;
*axis2_svc_ctx_get_conf_ctx = *WSO2::WSF::Cc::axis2_svc_ctx_get_conf_ctx;
*axis2_conf_ctx_get_conf = *WSO2::WSF::Cc::axis2_conf_ctx_get_conf;
*axis2_conf_get_module = *WSO2::WSF::Cc::axis2_conf_get_module;
*axiom_xml_reader_free = *WSO2::WSF::Cc::axiom_xml_reader_free;
*axis2_svc_client_set_proxy = *WSO2::WSF::Cc::axis2_svc_client_set_proxy;
*axutil_property_create_with_args = *WSO2::WSF::Cc::axutil_property_create_with_args;
*axutil_strdup_new = *WSO2::WSF::Cc::axutil_strdup_new;
*axis2_options_set_soap_version_uri = *WSO2::WSF::Cc::axis2_options_set_soap_version_uri;
*axutil_property_create = *WSO2::WSF::Cc::axutil_property_create;
*axutil_property_set_value = *WSO2::WSF::Cc::axutil_property_set_value;
*axutil_property_set_value_new = *WSO2::WSF::Cc::axutil_property_set_value_new;
*axis2_options_set_property_new = *WSO2::WSF::Cc::axis2_options_set_property_new;
*axis2_options_set_soap_version = *WSO2::WSF::Cc::axis2_options_set_soap_version;
*axutil_string_create = *WSO2::WSF::Cc::axutil_string_create;
*axis2_options_set_soap_action = *WSO2::WSF::Cc::axis2_options_set_soap_action;
*axis2_options_set_reply_to = *WSO2::WSF::Cc::axis2_options_set_reply_to;
*axis2_options_set_fault_to = *WSO2::WSF::Cc::axis2_options_set_fault_to;
*axis2_svc_client_get_last_response_has_fault = *WSO2::WSF::Cc::axis2_svc_client_get_last_response_has_fault;
*axis2_svc_client_get_last_response_soap_envelope = *WSO2::WSF::Cc::axis2_svc_client_get_last_response_soap_envelope;
*axiom_soap_envelope_get_body = *WSO2::WSF::Cc::axiom_soap_envelope_get_body;
*axiom_soap_body_get_fault = *WSO2::WSF::Cc::axiom_soap_body_get_fault;
*axis2_options_get_soap_version = *WSO2::WSF::Cc::axis2_options_get_soap_version;
*axiom_soap_fault_get_base_node = *WSO2::WSF::Cc::axiom_soap_fault_get_base_node;
*axiom_xml_writer_get_xml = *WSO2::WSF::Cc::axiom_xml_writer_get_xml;
*axiom_xml_writer_get_xml_new = *WSO2::WSF::Cc::axiom_xml_writer_get_xml_new;
*axis2_options_set_xml_parser_reset = *WSO2::WSF::Cc::axis2_options_set_xml_parser_reset;
*axis2_log_debug = *WSO2::WSF::Cc::axis2_log_debug;

# ------- VARIABLE STUBS --------

package WSO2::WSF::C;

*AXIS2_LOG_LEVEL_CRITICAL = *WSO2::WSF::Cc::AXIS2_LOG_LEVEL_CRITICAL;
*AXIS2_LOG_LEVEL_ERROR = *WSO2::WSF::Cc::AXIS2_LOG_LEVEL_ERROR;
*AXIS2_LOG_LEVEL_WARNING = *WSO2::WSF::Cc::AXIS2_LOG_LEVEL_WARNING;
*AXIS2_LOG_LEVEL_INFO = *WSO2::WSF::Cc::AXIS2_LOG_LEVEL_INFO;
*AXIS2_LOG_LEVEL_DEBUG = *WSO2::WSF::Cc::AXIS2_LOG_LEVEL_DEBUG;
*AXIS2_LOG_LEVEL_TRACE = *WSO2::WSF::Cc::AXIS2_LOG_LEVEL_TRACE;
*AXIS2_XML_PARSER_TYPE_BUFFER = *WSO2::WSF::Cc::AXIS2_XML_PARSER_TYPE_BUFFER;
*AXIS2_XML_PARSER_TYPE_FILE = *WSO2::WSF::Cc::AXIS2_XML_PARSER_TYPE_FILE;
*AXIS2_XML_PARSER_TYPE_DOC = *WSO2::WSF::Cc::AXIS2_XML_PARSER_TYPE_DOC;
*AXIOM_SOAP_VERSION_NOT_SET = *WSO2::WSF::Cc::AXIOM_SOAP_VERSION_NOT_SET;
*AXIOM_SOAP11 = *WSO2::WSF::Cc::AXIOM_SOAP11;
*AXIOM_SOAP12 = *WSO2::WSF::Cc::AXIOM_SOAP12;
*AXIS2_HTTP_GET = *WSO2::WSF::Cc::AXIS2_HTTP_GET;
*AXIS2_HTTP_METHOD = *WSO2::WSF::Cc::AXIS2_HTTP_METHOD;
*AXIS2_TRUE = *WSO2::WSF::Cc::AXIS2_TRUE;
*AXIS2_FALSE = *WSO2::WSF::Cc::AXIS2_FALSE;
*AXIS2_WSA_NAMESPACE_SUBMISSION = *WSO2::WSF::Cc::AXIS2_WSA_NAMESPACE_SUBMISSION;
*AXIS2_WSA_VERSION = *WSO2::WSF::Cc::AXIS2_WSA_VERSION;
*AXIOM_SOAP_STYLE_RPC_ENCODED = *WSO2::WSF::Cc::AXIOM_SOAP_STYLE_RPC_ENCODED;
*AXIOM_SOAP_STYLE_DOC_LITERAL_WRAPPED = *WSO2::WSF::Cc::AXIOM_SOAP_STYLE_DOC_LITERAL_WRAPPED;
*AXIS2_SCOPE = *WSO2::WSF::Cc::AXIS2_SCOPE;
*AXIS2_APPLICATION_SCOPE = *WSO2::WSF::Cc::AXIS2_APPLICATION_SCOPE;
*AXIS2_SESSION_SCOPE = *WSO2::WSF::Cc::AXIS2_SESSION_SCOPE;
*AXIS2_MESSAGE_SCOPE = *WSO2::WSF::Cc::AXIS2_MESSAGE_SCOPE;
*AXIS2_PHASE_SERVICE = *WSO2::WSF::Cc::AXIS2_PHASE_SERVICE;
*AXIS2_PHASE_TRANSPORT = *WSO2::WSF::Cc::AXIS2_PHASE_TRANSPORT;
*AXIS2_PHASE_GLOBAL = *WSO2::WSF::Cc::AXIS2_PHASE_GLOBAL;
*AXIS2_SESSION_CONTEXT_PROPERTY = *WSO2::WSF::Cc::AXIS2_SESSION_CONTEXT_PROPERTY;
*AXIS2_TRANSPORT_HTTP = *WSO2::WSF::Cc::AXIS2_TRANSPORT_HTTP;
*AXIS2_TRANSPORT_SMTP = *WSO2::WSF::Cc::AXIS2_TRANSPORT_SMTP;
*AXIS2_TRANSPORT_TCP = *WSO2::WSF::Cc::AXIS2_TRANSPORT_TCP;
*AXIS2_TRANSPORT_XMPP = *WSO2::WSF::Cc::AXIS2_TRANSPORT_XMPP;
*AXIS2_TRANSPORT_HTTPS = *WSO2::WSF::Cc::AXIS2_TRANSPORT_HTTPS;
*AXIS2_TRANSPORT_ENUM_HTTP = *WSO2::WSF::Cc::AXIS2_TRANSPORT_ENUM_HTTP;
*AXIS2_TRANSPORT_ENUM_SMTP = *WSO2::WSF::Cc::AXIS2_TRANSPORT_ENUM_SMTP;
*AXIS2_TRANSPORT_ENUM_TCP = *WSO2::WSF::Cc::AXIS2_TRANSPORT_ENUM_TCP;
*AXIS2_TRANSPORT_ENUM_XMPP = *WSO2::WSF::Cc::AXIS2_TRANSPORT_ENUM_XMPP;
*AXIS2_TRANSPORT_ENUM_HTTPS = *WSO2::WSF::Cc::AXIS2_TRANSPORT_ENUM_HTTPS;
*AXIS2_TRANSPORT_ENUM_MAX = *WSO2::WSF::Cc::AXIS2_TRANSPORT_ENUM_MAX;
*AXIS2_REQUEST_URL_PREFIX = *WSO2::WSF::Cc::AXIS2_REQUEST_URL_PREFIX;
*AXIS2_LISTSERVICES = *WSO2::WSF::Cc::AXIS2_LISTSERVICES;
*AXIS2_LIST_SERVICE_FOR_MODULE_ENGAMNET = *WSO2::WSF::Cc::AXIS2_LIST_SERVICE_FOR_MODULE_ENGAMNET;
*AXIS2_ADMIN_LISTSERVICES = *WSO2::WSF::Cc::AXIS2_ADMIN_LISTSERVICES;
*AXIS2_LIST_MODULES = *WSO2::WSF::Cc::AXIS2_LIST_MODULES;
*AXIS2_LIST_GLOABLLY_ENGAGED_MODULES = *WSO2::WSF::Cc::AXIS2_LIST_GLOABLLY_ENGAGED_MODULES;
*AXIS2_LIST_PHASES = *WSO2::WSF::Cc::AXIS2_LIST_PHASES;
*AXIS2_ENGAGE_GLOBAL_MODULE = *WSO2::WSF::Cc::AXIS2_ENGAGE_GLOBAL_MODULE;
*AXIS2_ENGAGE_MODULE_TO_SERVICE = *WSO2::WSF::Cc::AXIS2_ENGAGE_MODULE_TO_SERVICE;
*AXIS2_ENGAGE_MODULE_TO_SERVICE_GROUP = *WSO2::WSF::Cc::AXIS2_ENGAGE_MODULE_TO_SERVICE_GROUP;
*AXIS2_ADMIN_LOGIN = *WSO2::WSF::Cc::AXIS2_ADMIN_LOGIN;
*AXIS2_LIST_CONTEXTS = *WSO2::WSF::Cc::AXIS2_LIST_CONTEXTS;
*AXIS2_LOGOUT = *WSO2::WSF::Cc::AXIS2_LOGOUT;
*AXIS2_VIEW_GLOBAL_HANDLERS = *WSO2::WSF::Cc::AXIS2_VIEW_GLOBAL_HANDLERS;
*AXIS2_SELECT_SERVICE = *WSO2::WSF::Cc::AXIS2_SELECT_SERVICE;
*AXIS2_EDIR_SERVICE_PARA = *WSO2::WSF::Cc::AXIS2_EDIR_SERVICE_PARA;
*AXIS2_SELECT_SERVICE_FOR_PARA_EDIT = *WSO2::WSF::Cc::AXIS2_SELECT_SERVICE_FOR_PARA_EDIT;
*AXIS2_VIEW_SERVICE_HANDLERS = *WSO2::WSF::Cc::AXIS2_VIEW_SERVICE_HANDLERS;
*AXIS2_LIST_SERVIC_GROUPS = *WSO2::WSF::Cc::AXIS2_LIST_SERVIC_GROUPS;
*AXIS2_SERVICE_MAP = *WSO2::WSF::Cc::AXIS2_SERVICE_MAP;
*AXIS2_SERVICE_GROUP_MAP = *WSO2::WSF::Cc::AXIS2_SERVICE_GROUP_MAP;
*AXIS2_CONFIG_CONTEXT = *WSO2::WSF::Cc::AXIS2_CONFIG_CONTEXT;
*AXIS2_ACTION_MAPPING = *WSO2::WSF::Cc::AXIS2_ACTION_MAPPING;
*AXIS2_OUTPUT_ACTION_MAPPING = *WSO2::WSF::Cc::AXIS2_OUTPUT_ACTION_MAPPING;
*AXI2_FAULT_ACTION_MAPPING = *WSO2::WSF::Cc::AXI2_FAULT_ACTION_MAPPING;
*AXIS2_SERVICE = *WSO2::WSF::Cc::AXIS2_SERVICE;
*AXIS2_OPEARTION_MAP = *WSO2::WSF::Cc::AXIS2_OPEARTION_MAP;
*AXIS2_MODULE_ADDRESSING = *WSO2::WSF::Cc::AXIS2_MODULE_ADDRESSING;
*AXIS2_USER_NAME = *WSO2::WSF::Cc::AXIS2_USER_NAME;
*AXIS2_PASSWORD = *WSO2::WSF::Cc::AXIS2_PASSWORD;
*AXIS2_SINGLE_SERVICE = *WSO2::WSF::Cc::AXIS2_SINGLE_SERVICE;
*AXIS2_WSDL_CONTENT = *WSO2::WSF::Cc::AXIS2_WSDL_CONTENT;
*AXIS2_REQUEST_WSDL = *WSO2::WSF::Cc::AXIS2_REQUEST_WSDL;
*AXIS2_STYLE_RPC = *WSO2::WSF::Cc::AXIS2_STYLE_RPC;
*AXIS2_STYLE_DOC = *WSO2::WSF::Cc::AXIS2_STYLE_DOC;
*AXIS2_STYLE_MSG = *WSO2::WSF::Cc::AXIS2_STYLE_MSG;
*AXIS2_WSDL_MESSAGE_LABEL_IN = *WSO2::WSF::Cc::AXIS2_WSDL_MESSAGE_LABEL_IN;
*AXIS2_WSDL_MESSAGE_LABEL_OUT = *WSO2::WSF::Cc::AXIS2_WSDL_MESSAGE_LABEL_OUT;
*AXIS2_WSDL_MESSAGE_LABEL_MAX = *WSO2::WSF::Cc::AXIS2_WSDL_MESSAGE_LABEL_MAX;
*AXIS2_MEP_URI_IN_ONLY = *WSO2::WSF::Cc::AXIS2_MEP_URI_IN_ONLY;
*AXIS2_MEP_CONSTANT_IN_ONLY = *WSO2::WSF::Cc::AXIS2_MEP_CONSTANT_IN_ONLY;
*AXIS2_MEP_URI_ROBUST_IN_ONLY = *WSO2::WSF::Cc::AXIS2_MEP_URI_ROBUST_IN_ONLY;
*AXIS2_MEP_CONSTANT_ROBUST_IN_ONLY = *WSO2::WSF::Cc::AXIS2_MEP_CONSTANT_ROBUST_IN_ONLY;
*AXIS2_MEP_URI_IN_OUT = *WSO2::WSF::Cc::AXIS2_MEP_URI_IN_OUT;
*AXIS2_MEP_CONSTANT_IN_OUT = *WSO2::WSF::Cc::AXIS2_MEP_CONSTANT_IN_OUT;
*AXIS2_MEP_URI_IN_OPTIONAL_OUT = *WSO2::WSF::Cc::AXIS2_MEP_URI_IN_OPTIONAL_OUT;
*AXIS2_MEP_CONSTANT_IN_OPTIONAL_OUT = *WSO2::WSF::Cc::AXIS2_MEP_CONSTANT_IN_OPTIONAL_OUT;
*AXIS2_MEP_URI_OUT_ONLY = *WSO2::WSF::Cc::AXIS2_MEP_URI_OUT_ONLY;
*AXIS2_MEP_CONSTANT_OUT_ONLY = *WSO2::WSF::Cc::AXIS2_MEP_CONSTANT_OUT_ONLY;
*AXIS2_MEP_URI_ROBUST_OUT_ONLY = *WSO2::WSF::Cc::AXIS2_MEP_URI_ROBUST_OUT_ONLY;
*AXIS2_MEP_CONSTANT_ROBUST_OUT_ONLY = *WSO2::WSF::Cc::AXIS2_MEP_CONSTANT_ROBUST_OUT_ONLY;
*AXIS2_MEP_URI_OUT_IN = *WSO2::WSF::Cc::AXIS2_MEP_URI_OUT_IN;
*AXIS2_MEP_CONSTANT_OUT_IN = *WSO2::WSF::Cc::AXIS2_MEP_CONSTANT_OUT_IN;
*AXIS2_MEP_URI_OUT_OPTIONAL_IN = *WSO2::WSF::Cc::AXIS2_MEP_URI_OUT_OPTIONAL_IN;
*AXIS2_MEP_CONSTANT_OUT_OPTIONAL_IN = *WSO2::WSF::Cc::AXIS2_MEP_CONSTANT_OUT_OPTIONAL_IN;
*AXIS2_MEP_CONSTANT_INVALID = *WSO2::WSF::Cc::AXIS2_MEP_CONSTANT_INVALID;
*AXIS2_WSDL_MESSAGE_DIRECTION_IN = *WSO2::WSF::Cc::AXIS2_WSDL_MESSAGE_DIRECTION_IN;
*AXIS2_WSDL_MESSAGE_DIRECTION_OUT = *WSO2::WSF::Cc::AXIS2_WSDL_MESSAGE_DIRECTION_OUT;
*AXIS2_LOGGED = *WSO2::WSF::Cc::AXIS2_LOGGED;
*AXIS2_ENABLE_REST = *WSO2::WSF::Cc::AXIS2_ENABLE_REST;
*AXIS2_ENABLE_REST_THROUGH_GET = *WSO2::WSF::Cc::AXIS2_ENABLE_REST_THROUGH_GET;
*AXIS2_ENABLE_MTOM = *WSO2::WSF::Cc::AXIS2_ENABLE_MTOM;
*AXIS2_ATTACHMENT_TEMP_DIR = *WSO2::WSF::Cc::AXIS2_ATTACHMENT_TEMP_DIR;
*AXIS2_CACHE_ATTACHMENTS = *WSO2::WSF::Cc::AXIS2_CACHE_ATTACHMENTS;
*AXIS2_FILE_SIZE_THRESHOLD = *WSO2::WSF::Cc::AXIS2_FILE_SIZE_THRESHOLD;
*AXIS2_PERSIST_OP_CTX = *WSO2::WSF::Cc::AXIS2_PERSIST_OP_CTX;
*AXIS2_VALUE_TRUE = *WSO2::WSF::Cc::AXIS2_VALUE_TRUE;
*AXIS2_VALUE_FALSE = *WSO2::WSF::Cc::AXIS2_VALUE_FALSE;
*AXIS2_CONTAINER_MANAGED = *WSO2::WSF::Cc::AXIS2_CONTAINER_MANAGED;
*AXIS2_RESPONSE_WRITTEN = *WSO2::WSF::Cc::AXIS2_RESPONSE_WRITTEN;
*AXIS2_TESTING_PATH = *WSO2::WSF::Cc::AXIS2_TESTING_PATH;
*AXIS2_TESTING_REPOSITORY = *WSO2::WSF::Cc::AXIS2_TESTING_REPOSITORY;
*AXIS2_LOAD_SVC_STARTUP = *WSO2::WSF::Cc::AXIS2_LOAD_SVC_STARTUP;
*AXIS2_GET_PARAMETER_OP = *WSO2::WSF::Cc::AXIS2_GET_PARAMETER_OP;
*AXIS2_GET_PARAMETER_URL = *WSO2::WSF::Cc::AXIS2_GET_PARAMETER_URL;
*AXIS2_NAMESPACE_PREFIX = *WSO2::WSF::Cc::AXIS2_NAMESPACE_PREFIX;
*AXIS2_NAMESPACE_URI = *WSO2::WSF::Cc::AXIS2_NAMESPACE_URI;
*AXIS2_SVC_GRP_ID = *WSO2::WSF::Cc::AXIS2_SVC_GRP_ID;
*AXIS2_RESPONSE_SOAP_ENVELOPE = *WSO2::WSF::Cc::AXIS2_RESPONSE_SOAP_ENVELOPE;
*AXIS2_HANDLER_ALREADY_VISITED = *WSO2::WSF::Cc::AXIS2_HANDLER_ALREADY_VISITED;
1;
